### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-dom-and-events-the-dom-is-a-tree-readme#3]
First off, a var that should be changed to let, for consistency (last sentence): 

Inspect the web page again, this time making note of a className. Get all elements with that className and give 'em a look. Remember, you can use a for loop to loop through them. (You can also assign the return value of document.getElementsByClassName() to a variable: var elements = document.getElementsByClassName('banner').)

Second, I'm not new to js/html but I feel like these lessons should be edited some-- the directions about working in the dev tools are not clear enough -- and I'm used to doing this. It's actually kind of tough to both find something in elements and then edit using js in console, you're going back and forth. If there's a tip, then let readers know. It's kind of like how back in the js section, the codealongs were really hard to code along to, it's as if they weren't written while also doing it. I didn't leave a note there because well, I wanted to get through the labs and lessons because I knew I'd have to spend lots of time in the docs and looking up videos on the topics. This whole section post-Rails feels like it needs a few more iterations. I know it's tough; I've had some experience writing about code and doing how-to's. It's a challenge to find clarity and to write with a reader fully in mind. The Ruby/Rails sections do this so well but the JS section feels like I'm in a different school. 

Anyway, passing this on in case it's helpful. I've left some typo edits along the way; my eye just catches them. I've stopped, but I'll pass on that this section could use a good edit. To end, please take all this as a caring student (with a background in writing and publishing) giving constructive feedback. Now back to coding,  I can't wait to get to the sections on Ajax and API's!

**Comment by cjbrock** [comment]
Hey @MiriamPeskowitz!

First off, thank you for your edit. I've made that change.

Secondly, thank you for your efforts on copy editing and such. I appreciate all of your issues up until this point - it takes a *ton* of effort to make those notes and we appreciate all of them. We've made all the changes you've noted up until this point and we'll continue to make any that you catch in the future, if you decide to note them! And if you want to make larger scale comments like the ones above, I'd love to hear those as well. As you know, writing a curriculum to this scale is a massive undertaking and one of our most valuable resources is our students. I was a section lead for two years before I came to work for curriculum and the knowledge I draw on every day is how I worked with my students online. I try to take all feedback as constructive, so please feel free to leave anything you see. You can also feel free to reach out to me directly at corinna@flatironschool.com. Thank you for being part of our community!
// <3 Corinna

**Comment by MiriamPeskowitz** [comment]
Hi Corinna, 

Thanks for your nice note! 

I totally know how much effort and iteration goes into making the lessons and labs. I just finished a book that explains code and tech to middle school girls and beginners of all ages, and it took forever to get everything even half-correct, and to take in different readers’ takes on in. I’ll keep sending in issues — August has been a slow month for me, and I had other work, but I hope to step it up now — I’ve got to graduate! 

Big picture — the labs are way more complex than the lessons, like several notches up. In the Ruby/Rails sections, there was a stretch in the labs, but not as much as here. Then, to exacerbate the problem, the tech coaches are not as strong at js as they are at Ruby/Rails, so often they can’t provide that much help. There’s definitely some frustration among the students, and I know that Alice B is taking that feedback to the curriculum team. There was a study group this morning and all this came up. Alice has been great and very supportive, and we’re all getting through it. It must be really hard to figure out how much or little to include. 

I love Flatiron, glad to contribute these small feedbacks, and my eye just catches the typos and such because I’m a writer by trade. Good luck with all that you’re doing! It’s awesome and much appreciated. 

Miriam 

Miriam Peskowitz

NYTimes Bestselling Author, The Daring Book for Girls <https://www.amazon.com/Daring-Book-Girls-Andrea-Buchanan/dp/0062208969/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1530814741&sr=8-1>
Code Like a Girl <https://www.amazon.com/gp/product/1524713899/ref=x_gr_w_bb_sout?ie=UTF8&tag=x_gr_w_bb_sout-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1524713899&SubscriptionId=1MGPYB6YW3HWK55XCGG2> coming in March 2019!
miriam5000@gmail.com


On Aug 31, 2018, at 2:27 PM, Corinna Brock <notifications@github.com> wrote:

Hey @MiriamPeskowitz <https://github.com/MiriamPeskowitz>!

First off, thank you for your edit. I've made that change.

Secondly, thank you for your efforts on copy editing and such. I appreciate all of your issues up until this point - it takes a ton of effort to make those notes and we appreciate all of them. We've made all the changes you've noted up until this point and we'll continue to make any that you catch in the future, if you decide to note them! And if you want to make larger scale comments like the ones above, I'd love to hear those as well. As you know, writing a curriculum to this scale is a massive undertaking and one of our most valuable resources is our students. I was a section lead for two years before I came to work for curriculum and the knowledge I draw on every day is how I worked with my students online. I try to take all feedback as constructive, so please feel free to leave anything you see. You can also feel free to reach out to me directly at corinna@flatironschool.com <mailto:corinna@flatironschool.com>. Thank you for being part of our community!
// <3 Corinna
